env:
  browser: true
  es2021: true
extends:
  - standard
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
settings:
  react:
    version: detect
