install:
	npm ci

start:
	npm run start

build:
	npm run build

lint:
	npx eslint --ext js,jsx --no-eslintrc --config .eslintrc.yml .

start-build:
	npx serve -s build

test:
	npx playwright test __tests__/10-application.test.js